### ISSUE TITLE
build issue on heroku - undefined: jsonutil.UnmarshalIoReader

### ISSUE THREAD

**Issue by julbr** [grokify/go-ringcentral-client#36]
When attempting to deploy to Heroku, I get this error from Heroku's build log:
```
# myproject/vendor/github.com/grokify/oauth2more/ringcentral
vendor/github.com/grokify/oauth2more/ringcentral/ringcentral_client.go:246:11: undefined: jsonutil.UnmarshalIoReader
```

lib is managed with dep:
$dep version github.com/grokify/go-ringcentral
```
dep:
 version     : v0.4.1
 build date  : 2018-01-27
 git hash    : 37d9ea0
 go version  : go1.9.3
 go compiler : gc
 platform    : darwin/amd64
```

Gopkg.toml:
```
[[constraint]]
  branch = "master"
  name = "github.com/grokify/go-ringcentral"
```

Any ideas?

**Comment by grokify** [comment]
Can you run it locally? I'm wondering if this is an issue with using `dep`.

Is `dep` not packaging up the dependencies properly. Do you see `gotilla` in the `vendor` folder?

The following run fine for me locally.
* Locally running `go test -v ./...`
* Travis CI tests pass for `go-ringcentral` incl. Go 1.9.7: https://travis-ci.org/grokify/go-ringcentral
* Travis CI tests pass for `oauth2more` incl. Go 1.9.7: https://travis-ci.org/grokify/oauth2more

I've only used `godep` with Heroku but may look into running a test project on Heroku with `dep`.

**Comment by julbr** [comment]
This was fixed by https://github.com/grokify/gotilla/issues/1. With gotilla up to date, everything started working with very minor updates to the code.
