### ISSUE TITLE
Error during install: undefined: timeutil.TimeRFC3339Zero

### ISSUE THREAD

**Issue by julbr** [grokify/go-ringcentral-client#38]
Trying to install the latest lib for ringcentral API v1 with:
* `go get github.com/grokify/go-ringcentral/office/v1/client` **<- works**
* `go get github.com/grokify/go-ringcentral/office/v1/util` **<- returns the error below**

```
# github.com/grokify/oauth2more
../github.com/grokify/oauth2more/basicauth.go:43:16: undefined: timeutil.TimeRFC3339Zero
../github.com/grokify/oauth2more/oauth2more.go:242:16: undefined: timeutil.TimeRFC3339Zero
```

I installed `timeutil` with `go get github.com/grokify/gotilla/time/timeutil` but no difference.

---
`go get github.com/grokify/oauth2more` yields the same errors:
```
# github.com/grokify/oauth2more
../github.com/grokify/oauth2more/basicauth.go:43:16: undefined: timeutil.TimeRFC3339Zero
../github.com/grokify/oauth2more/oauth2more.go:242:16: undefined: timeutil.TimeRFC3339Zero
```

**Comment by grokify** [comment]
@julbr Thanks for reporting this.

This should be resolved now with the introduction of dependency management with Go Modules.

As part of the move to Go Modules, this repo and package has been renamed to `github.com/grokify/go-ringcentral-client`. Please use this as `go-ringcentral-client` with version `0.1.0` or later
